sudo: false
language: node_js
node_js:
  - '0.12'
before_script: 
install: true
cache:
  directories:
    - node_modules
    - $HOME/.npm
script:
  - npm install grunt-cli -g
  - npm install
  - grunt travis
after_success:
  - node trigger-build.js